server:
  port: 10002





spring:
  application:
    name: user-management
  cloud:
    loadbalancer:
      ribbon:
        enable: false
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/professionals
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true
    format-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

    #CREATE : deleting first then recreating tables
    #UPDATE : if table exists it will update if any change otherwise it will create table again. (default)
    #CREATE-DROP


